version: "3.9"
services:
  app:
    container_name: optimizely-fe-agent-runner
    restart: unless-stopped
    build:
      context: .
      target: runner
    image: optimizely-fe-agent:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
